<!-- Main content -->
<template>
<!-- Main content -->
  <div class="content">
    <div class="row">
      <div class="col-md-12">
        <div class="box">
          <div class="box-header with-border"> 
            <div class="alert alert-info alert-dismissible">
              <button type="button" class="close" data-dismiss="alert" aria-hidden="true"></button>
              <h4>Tabel 5 - JUMLAH KUNJUNGAN PASIEN BARU RAWAT JALAN, RAWAT INAP, DAN KUNJUNGAN GANGGUAN JIWA DI SARANA PELAYANAN KESEHATAN</h4>
              <div class="row">
                <div class="col-md-6">
                  <h5>Tabel dibawah ini rekap perbulan dari setiap Desa</h5>
                  <h5> Pilih Bulan dan Tahun pada periode yang di inginkan dan klik tombol <strong>Cari</strong></h5>
                  <h5> Tombol <strong><span class="badge bg-navy"><i class="fa fa-fw fa-file-excel-o"></i></span> export to excel</strong> digunakan untuk mengunduh tabel di bawah</h5>
                  <h5> Tombol <strong> <span class="badge bg-green"><i class="fa fa-fw fa-plus-circle"></i></span> edit/tambah data</strong> digunakan untuk menambah data</h5>
                </div>
                <div class="col-md-6">
                  <h5> Tombol <strong><span class="badge bg-orange"><i class="fa fa-fw fa-edit"></i></span> edit </strong> digunakan untuk mengubah isi tabel </h5>
                  <h5> Tombol <strong> <span class="badge bg-red"><i class="fa fa-fw fa-trash"></i></span> happus</strong> digunakan untuk menghapus isi tabel </h5>
                </div>
              </div>
            </div>
            <div class="col-md-3">
              <div class="form-group">
                  <select v-model="PILIH_BULAN" class="form-control">
                    <option selected="selected">Pilih Bulan</option>
                    <option value="1">Januari</option>
                    <option value="2">Februari</option>
                    <option value="3">Maret</option>
                    <option value="4">April</option>
                    <option value="5">Mei</option>
                    <option value="6">Juni</option>
                    <option value="7">Juli</option>
                    <option value="8">Agustus</option>
                    <option value="9">September</option>
                    <option value="10">Oktober</option>
                    <option value="11">November</option>
                    <option value="12">Desember</option>
                  </select>
              </div>
            </div>
            <div class="col-md-3">
              <div class="form-group">
                  <select v-model="PILIH_TAHUN" class="form-control">
                    <option selected="selected">Pilih Tahun</option>
                    <option value="2019">2019</option>
                    <option value="2020">2020</option>
                    <option value="2021">2021</option>
                  </select>
              </div>
            </div>
            <div class="col-md-3">
              <div class="form-group">
                <select v-model="JENIS_FASKES" class="form-control">
                  <option value="pilih">Pilih Jenis Faskes</option>
                  <option value="rs_umum">Rs Umum</option>
                  <option value="rs_khusus">Rs Khusus</option>
                  <option value="klinik_utama">Klinik Utama</option>
                  <option value="puskesmas">Puskesmas</option>
                  <option value="klinik_pratama">Klinik Pratama</option>
                  <option value="p_spesialis">Praktik Mandiri Dokter Spesialis</option>
                  <option value="p_dokter">Praktik Mandiri Dokter</option>
                  <option value="p_gigi">Praktik Mandiri Dokter Gigi</option>
                  <option value="p_bidan">Praktik Mandiri Bidan</option>
                </select>
              </div>
            </div>
            <div class="col-md-6">
              <button @click="cariTanggal()" type="button" class="btn btn-primary btn-md"><i class="fa fa-fw fa-search"></i> Cari</button>
              <button type="button" class="btn bg-navy btn-md"><i class="fa fa-fw fa-file-excel-o"></i>Export to Excel</button>
              <router-link to="/table5/input"><a class="btn btn-success btn-md"><i class="fa fa-fw fa-plus-circle"></i> Edit/Tambah Data </a></router-link>
            </div>             
          </div>
          <!-- /.box-header -->
          <div class="box-body table-responsive no-padding">
            <table class="table table-striped">
              <thead class="thead-dark">
                <tr>
                  <th style="text-align: center;" colspan="6">JUMLAH KUNJUNGAN<br></th>
                  <th style="text-align: center;" colspan="3">KUNJUNGAN GANGGUAN JIWA</th>
                </tr>
                <tr>
                  <td style="text-align: center;" colspan="3">RAWAT JALAN</td>
                  <td style="text-align: center;" colspan="3">RAWAT INAP</td>
                  <td style="text-align: center;" colspan="3">JUMLAH</td>
                </tr>
                <tr>
                  <td style="text-align: center;">L</td>
                  <td style="text-align: center;">P</td>
                  <td style="text-align: center;">L+P</td>
                  <td style="text-align: center;">L</td>
                  <td style="text-align: center;">P</td>
                  <td style="text-align: center;">L+P</td>
                  <td style="text-align: center;">L</td>
                  <td style="text-align: center;">P</td>
                  <td style="text-align: center;">L+P</td>
                </tr>                                 
              </thead>
              <tbody>                  
                <tr v-if="JENIS_FASKES == 'rs_umum'">
                  <td style="text-align: center;">{{JUMLAH_KUNJUNGAN_RAWAT_JALAN_LAKI_FASILITAS_PELAYANAN_KESEHATAN_TINGKAT_LANJUT_RS_UMUM}}</td>
                  <td style="text-align: center;">{{JUMLAH_KUNJUNGAN_RAWAT_JALAN_PEREMPUAN_FASILITAS_PELAYANAN_KESEHATAN_TINGKAT_LANJUT_RS_UMUM}}</td>
                  <td style="text-align: center;">{{parseInt(JUMLAH_KUNJUNGAN_RAWAT_JALAN_PEREMPUAN_FASILITAS_PELAYANAN_KESEHATAN_TINGKAT_LANJUT_RS_UMUM) + parseInt(JUMLAH_KUNJUNGAN_RAWAT_JALAN_LAKI_FASILITAS_PELAYANAN_KESEHATAN_TINGKAT_LANJUT_RS_UMUM)}}</td>
                  <td style="text-align: center;">{{JUMLAH_KUNJUNGAN_RAWAT_INAP_LAKI_FASILITAS_PELAYANAN_KESEHATAN_TINGKAT_LANJUT_RS_UMUM}}</td>
                  <td style="text-align: center;">{{JUMLAH_KUNJUNGAN_RAWAT_INAP_PEREMPUAN_FASILITAS_PELAYANAN_KESEHATAN_TINGKAT_LANJUT_RS_UMUM}}</td>
                  <td style="text-align: center;">{{parseInt(JUMLAH_KUNJUNGAN_RAWAT_INAP_LAKI_FASILITAS_PELAYANAN_KESEHATAN_TINGKAT_LANJUT_RS_UMUM) + parseInt(JUMLAH_KUNJUNGAN_RAWAT_INAP_PEREMPUAN_FASILITAS_PELAYANAN_KESEHATAN_TINGKAT_LANJUT_RS_UMUM)}}</td>
                  <td style="text-align: center;">{{KUNJUNGAN_GANGGUAN_JIWA_JUMLAH_LAKI_FASILITAS_PELAYANAN_KESEHATAN_TINGKAT_LANJUT_RS_UMUM}}</td>
                  <td style="text-align: center;">{{KUNJUNGAN_GANGGUAN_JIWA_JUMLAH_PEREMPUAN_FASILITAS_PELAYANAN_KESEHATAN_TINGKAT_LANJUT_RS_UMUM}}</td>
                  <td style="text-align: center;">{{parseInt(KUNJUNGAN_GANGGUAN_JIWA_JUMLAH_PEREMPUAN_FASILITAS_PELAYANAN_KESEHATAN_TINGKAT_LANJUT_RS_UMUM) + parseInt(KUNJUNGAN_GANGGUAN_JIWA_JUMLAH_LAKI_FASILITAS_PELAYANAN_KESEHATAN_TINGKAT_LANJUT_RS_UMUM)}}</td>
                </tr>
                <tr v-if="JENIS_FASKES == 'rs_khusus'">
                  <td style="text-align: center;">{{JUMLAH_KUNJUNGAN_RAWAT_JALAN_LAKI_FASILITAS_PELAYANAN_KESEHATAN_TINGKAT_LANJUT_RS_KHUSUS}}</td>
                  <td style="text-align: center;">{{JUMLAH_KUNJUNGAN_RAWAT_JALAN_PEREMPUAN_FASILITAS_PELAYANAN_KESEHATAN_TINGKAT_LANJUT_RS_KHUSUS}}</td>
                  <td style="text-align: center;">{{parseInt(JUMLAH_KUNJUNGAN_RAWAT_JALAN_PEREMPUAN_FASILITAS_PELAYANAN_KESEHATAN_TINGKAT_LANJUT_RS_KHUSUS) + parseInt(JUMLAH_KUNJUNGAN_RAWAT_JALAN_LAKI_FASILITAS_PELAYANAN_KESEHATAN_TINGKAT_LANJUT_RS_KHUSUS)}}</td>
                  <td style="text-align: center;">{{JUMLAH_KUNJUNGAN_RAWAT_INAP_LAKI_FASILITAS_PELAYANAN_KESEHATAN_TINGKAT_LANJUT_RS_KHUSUS}}</td>
                  <td style="text-align: center;">{{JUMLAH_KUNJUNGAN_RAWAT_INAP_PEREMPUAN_FASILITAS_PELAYANAN_KESEHATAN_TINGKAT_LANJUT_RS_KHUSUS}}</td>
                  <td style="text-align: center;">{{parseInt(JUMLAH_KUNJUNGAN_RAWAT_INAP_LAKI_FASILITAS_PELAYANAN_KESEHATAN_TINGKAT_LANJUT_RS_KHUSUS) + parseInt(JUMLAH_KUNJUNGAN_RAWAT_INAP_PEREMPUAN_FASILITAS_PELAYANAN_KESEHATAN_TINGKAT_LANJUT_RS_KHUSUS)}}</td>
                  <td style="text-align: center;">{{KUNJUNGAN_GANGGUAN_JIWA_JUMLAH_LAKI_FASILITAS_PELAYANAN_KESEHATAN_TINGKAT_LANJUT_RS_KHUSUS}}</td>
                  <td style="text-align: center;">{{KUNJUNGAN_GANGGUAN_JIWA_JUMLAH_PEREMPUAN_FASILITAS_PELAYANAN_KESEHATAN_TINGKAT_LANJUT_RS_KHUSUS}}</td>
                  <td style="text-align: center;">{{parseInt(KUNJUNGAN_GANGGUAN_JIWA_JUMLAH_PEREMPUAN_FASILITAS_PELAYANAN_KESEHATAN_TINGKAT_LANJUT_RS_KHUSUS) + parseInt(KUNJUNGAN_GANGGUAN_JIWA_JUMLAH_LAKI_FASILITAS_PELAYANAN_KESEHATAN_TINGKAT_LANJUT_RS_KHUSUS)}}</td>
                </tr>    
                <tr v-if="JENIS_FASKES == 'klinik_utama'">
                  <td style="text-align: center;">{{JUMLAH_KUNJUNGAN_RAWAT_JALAN_LAKI_FASILITAS_PELAYANAN_KESEHATAN_TINGKAT_LANJUT_KLINIK_UTAMA}}</td>
                  <td style="text-align: center;">{{JUMLAH_KUNJUNGAN_RAWAT_JALAN_PEREMPUAN_FASILITAS_PELAYANAN_KESEHATAN_TINGKAT_LANJUT_KLINIK_UTAMA}}</td>
                  <td style="text-align: center;">{{parseInt(JUMLAH_KUNJUNGAN_RAWAT_JALAN_PEREMPUAN_FASILITAS_PELAYANAN_KESEHATAN_TINGKAT_LANJUT_KLINIK_UTAMA) + parseInt(JUMLAH_KUNJUNGAN_RAWAT_JALAN_LAKI_FASILITAS_PELAYANAN_KESEHATAN_TINGKAT_LANJUT_KLINIK_UTAMA)}}</td>
                  <td style="text-align: center;">{{JUMLAH_KUNJUNGAN_RAWAT_INAP_LAKI_FASILITAS_PELAYANAN_KESEHATAN_TINGKAT_LANJUT_KLINIK_UTAMA}}</td>
                  <td style="text-align: center;">{{JUMLAH_KUNJUNGAN_RAWAT_INAP_PEREMPUAN_FASILITAS_PELAYANAN_KESEHATAN_TINGKAT_LANJUT_KLINIK_UTAMA}}</td>
                  <td style="text-align: center;">{{parseInt(JUMLAH_KUNJUNGAN_RAWAT_INAP_LAKI_FASILITAS_PELAYANAN_KESEHATAN_TINGKAT_LANJUT_KLINIK_UTAMA) + parseInt(JUMLAH_KUNJUNGAN_RAWAT_INAP_PEREMPUAN_FASILITAS_PELAYANAN_KESEHATAN_TINGKAT_LANJUT_KLINIK_UTAMA)}}</td>
                  <td style="text-align: center;">{{KUNJUNGAN_GANGGUAN_JIWA_JUMLAH_LAKI_FASILITAS_PELAYANAN_KESEHATAN_TINGKAT_LANJUT_KLINIK_UTAMA}}</td>
                  <td style="text-align: center;">{{KUNJUNGAN_GANGGUAN_JIWA_JUMLAH_PEREMPUAN_FASILITAS_PELAYANAN_KESEHATAN_TINGKAT_LANJUT_KLINIK_UTAMA}}</td>
                  <td style="text-align: center;">{{parseInt(KUNJUNGAN_GANGGUAN_JIWA_JUMLAH_PEREMPUAN_FASILITAS_PELAYANAN_KESEHATAN_TINGKAT_LANJUT_KLINIK_UTAMA) + parseInt(KUNJUNGAN_GANGGUAN_JIWA_JUMLAH_LAKI_FASILITAS_PELAYANAN_KESEHATAN_TINGKAT_LANJUT_KLINIK_UTAMA)}}</td>
                </tr>                                            
              </tbody>
            </table>
          </div>
          <!-- /.box-body -->
        </div>
        <!-- /.box -->         
      </div>
    </div>
      <!-- /.modal -->
  </div>
  <!-- /.content -->
</template>
<script>
export default {
  name: 'Table5',
  data() {
    return {
      USERNAME: '',
      JENIS_RS: '',
      PILIH_BULAN: '1',
      PILIH_TAHUN: '2019',
      NAMA_RUMAH_SAKIT: '',
      JENIS_FASKES: 'pilih',     
      KUNJUNGAN_GANGGUAN_JIWA_JUMLAH_LP_FASILITAS_PELAYANAN_KESEHATAN_TINGKAT_LANJUT_RS_UMUM: 0, 
      JUMLAH_KUNJUNGAN_RAWAT_JALAN_LAKI_FASILITAS_PELAYANAN_KESEHATAN_TINGKAT_PERTAMA_PUSKESMAS: 0,
      JUMLAH_KUNJUNGAN_RAWAT_JALAN_LAKI_FASILITAS_PELAYANAN_KESEHATAN_TINGKAT_PERTAMA_KLINIK_PRATAMA: '1',
      JUMLAH_KUNJUNGAN_RAWAT_JALAN_LAKI_FASILITAS_PELAYANAN_KESEHATAN_TINGKAT_PERTAMA_PRAKTIK_MANDIRI_DOKTER: '2019',
      JUMLAH_KUNJUNGAN_RAWAT_JALAN_LAKI_FASILITAS_PELAYANAN_KESEHATAN_TINGKAT_PERTAMA_PRAKTIK_MANDIRI_DOKTER_GIGI: 0,
      JUMLAH_KUNJUNGAN_RAWAT_JALAN_LAKI_FASILITAS_PELAYANAN_KESEHATAN_TINGKAT_PERTAMA_PRAKTIK_MANDIRI_BIDAN: 0,
      JUMLAH_KUNJUNGAN_RAWAT_JALAN_LAKI_FASILITAS_PELAYANAN_KESEHATAN_TINGKAT_LANJUT_KLINIK_UTAMA: 0,
      JUMLAH_KUNJUNGAN_RAWAT_JALAN_LAKI_FASILITAS_PELAYANAN_KESEHATAN_TINGKAT_LANJUT_RS_UMUM: 0,
      JUMLAH_KUNJUNGAN_RAWAT_JALAN_LP_FASILITAS_PELAYANAN_KESEHATAN_TINGKAT_LANJUT_RS_UMUM: 0,
      JUMLAH_KUNJUNGAN_RAWAT_JALAN_LAKI_FASILITAS_PELAYANAN_KESEHATAN_TINGKAT_LANJUT_RS_KHUSUS: 0,
      JUMLAH_KUNJUNGAN_RAWAT_JALAN_LAKI_FASILITAS_PELAYANAN_KESEHATAN_TINGKAT_LANJUT_PRAKTIK_MANDIRI_DOKTER_SPESIALIS: 0,
      JUMLAH_KUNJUNGAN_RAWAT_JALAN_PEREMPUAN_FASILITAS_PELAYANAN_KESEHATAN_TINGKAT_PERTAMA_PUSKESMAS: 0,
      JUMLAH_KUNJUNGAN_RAWAT_JALAN_PEREMPUAN_FASILITAS_PELAYANAN_KESEHATAN_TINGKAT_PERTAMA_KLINIK_PRATAMA: 0,
      JUMLAH_KUNJUNGAN_RAWAT_JALAN_PEREMPUAN_FASILITAS_PELAYANAN_KESEHATAN_TINGKAT_PERTAMA_PRAKTIK_MANDIRI_DOKTER: 0,
      JUMLAH_KUNJUNGAN_RAWAT_JALAN_PEREMPUAN_FASILITAS_PELAYANAN_KESEHATAN_TINGKAT_PERTAMA_PRAKTIK_MANDIRI_DOKTER_GIGI: 0,
      JUMLAH_KUNJUNGAN_RAWAT_JALAN_PEREMPUAN_FASILITAS_PELAYANAN_KESEHATAN_TINGKAT_PERTAMA_PRAKTIK_MANDIRI_BIDAN: 0,
      JUMLAH_KUNJUNGAN_RAWAT_JALAN_PEREMPUAN_FASILITAS_PELAYANAN_KESEHATAN_TINGKAT_LANJUT_KLINIK_UTAMA: 0,
      JUMLAH_KUNJUNGAN_RAWAT_JALAN_PEREMPUAN_FASILITAS_PELAYANAN_KESEHATAN_TINGKAT_LANJUT_RS_UMUM: 0,
      JUMLAH_KUNJUNGAN_RAWAT_JALAN_PEREMPUAN_FASILITAS_PELAYANAN_KESEHATAN_TINGKAT_LANJUT_RS_KHUSUS: 0,
      JUMLAH_KUNJUNGAN_RAWAT_JALAN_PEREMPUAN_FASILITAS_PELAYANAN_KESEHATAN_TINGKAT_LANJUT_PRAKTIK_MANDIRI_DOKTER_SPESIALIS: 0,
      JUMLAH_KUNJUNGAN_RAWAT_JALAN_LAKI_PEREMPUAN_FASILITAS_PELAYANAN_KESEHATAN_TINGKAT_PERTAMA_PUSKESMAS: 0,
      JUMLAH_KUNJUNGAN_RAWAT_JALAN_LAKI_PEREMPUAN_FASILITAS_PELAYANAN_KESEHATAN_TINGKAT_PERTAMA_KLINIK_PRATAMA: 0,
      JUMLAH_KUNJUNGAN_RAWAT_JALAN_LAKI_PEREMPUAN_FASILITAS_PELAYANAN_KESEHATAN_TINGKAT_PERTAMA_PRAKTIK_MANDIRI_DOKTER: 0,
      JUMLAH_KUNJUNGAN_RAWAT_JALAN_LAKI_PEREMPUAN_FASILITAS_PELAYANAN_KESEHATAN_TINGKAT_PERTAMA_PRAKTIK_MANDIRI_DOKTER_GIGI: 0,
      JUMLAH_KUNJUNGAN_RAWAT_JALAN_LAKI_PEREMPUAN_FASILITAS_PELAYANAN_KESEHATAN_TINGKAT_PERTAMA_PRAKTIK_MANDIRI_BIDAN: 0,
      JUMLAH_KUNJUNGAN_RAWAT_JALAN_LAKI_PEREMPUAN_FASILITAS_PELAYANAN_KESEHATAN_TINGKAT_LANJUT_KLINIK_UTAMA: 0,
      JUMLAH_KUNJUNGAN_RAWAT_JALAN_LAKI_PEREMPUAN_FASILITAS_PELAYANAN_KESEHATAN_TINGKAT_LANJUT_RS_UMUM: 0,
      JUMLAH_KUNJUNGAN_RAWAT_JALAN_LAKI_PEREMPUAN_FASILITAS_PELAYANAN_KESEHATAN_TINGKAT_LANJUT_RS_KHUSUS: 0,
      JUMLAH_KUNJUNGAN_RAWAT_JALAN_LAKI_PEREMPUAN_FASILITAS_PELAYANAN_KESEHATAN_TINGKAT_LANJUT_PRAKTIK_MANDIRI_DOKTER_SPESIALIS: 0,
      JUMLAH_KUNJUNGAN_RAWAT_INAP_LAKI_FASILITAS_PELAYANAN_KESEHATAN_TINGKAT_PERTAMA_PUSKESMAS: 0,
      JUMLAH_KUNJUNGAN_RAWAT_INAP_LAKI_FASILITAS_PELAYANAN_KESEHATAN_TINGKAT_PERTAMA_KLINIK_PRATAMA: 0,
      JUMLAH_KUNJUNGAN_RAWAT_INAP_LAKI_FASILITAS_PELAYANAN_KESEHATAN_TINGKAT_PERTAMA_PRAKTIK_MANDIRI_DOKTER: 0,
      JUMLAH_KUNJUNGAN_RAWAT_INAP_LAKI_FASILITAS_PELAYANAN_KESEHATAN_TINGKAT_PERTAMA_PRAKTIK_MANDIRI_DOKTER_GIGI: 0,
      JUMLAH_KUNJUNGAN_RAWAT_INAP_LAKI_FASILITAS_PELAYANAN_KESEHATAN_TINGKAT_PERTAMA_PRAKTIK_MANDIRI_BIDAN: 0,
      JUMLAH_KUNJUNGAN_RAWAT_INAP_LAKI_FASILITAS_PELAYANAN_KESEHATAN_TINGKAT_LANJUT_KLINIK_UTAMA: 0,
      JUMLAH_KUNJUNGAN_RAWAT_INAP_LAKI_FASILITAS_PELAYANAN_KESEHATAN_TINGKAT_LANJUT_RS_UMUM: 0,
      JUMLAH_KUNJUNGAN_RAWAT_INAP_LP_FASILITAS_PELAYANAN_KESEHATAN_TINGKAT_LANJUT_RS_UMUM: 0,
      JUMLAH_KUNJUNGAN_RAWAT_INAP_LAKI_FASILITAS_PELAYANAN_KESEHATAN_TINGKAT_LANJUT_RS_KHUSUS: 0,
      JUMLAH_KUNJUNGAN_RAWAT_INAP_LAKI_FASILITAS_PELAYANAN_KESEHATAN_TINGKAT_LANJUT_PRAKTIK_MANDIRI_DOKTER_SPESIALIS: 0,
      JUMLAH_KUNJUNGAN_RAWAT_INAP_PEREMPUAN_FASILITAS_PELAYANAN_KESEHATAN_TINGKAT_PERTAMA_PUSKESMAS: 0,
      JUMLAH_KUNJUNGAN_RAWAT_INAP_PEREMPUAN_FASILITAS_PELAYANAN_KESEHATAN_TINGKAT_PERTAMA_KLINIK_PRATAMA: 0,
      JUMLAH_KUNJUNGAN_RAWAT_INAP_PEREMPUAN_FASILITAS_PELAYANAN_KESEHATAN_TINGKAT_PERTAMA_PRAKTIK_MANDIRI_DOKTER: 0,
      JUMLAH_KUNJUNGAN_RAWAT_INAP_PEREMPUAN_FASILITAS_PELAYANAN_KESEHATAN_TINGKAT_PERTAMA_PRAKTIK_MANDIRI_DOKTER_GIGI: 0,
      JUMLAH_KUNJUNGAN_RAWAT_INAP_PEREMPUAN_FASILITAS_PELAYANAN_KESEHATAN_TINGKAT_PERTAMA_PRAKTIK_MANDIRI_BIDAN: 0,
      JUMLAH_KUNJUNGAN_RAWAT_INAP_PEREMPUAN_FASILITAS_PELAYANAN_KESEHATAN_TINGKAT_LANJUT_KLINIK_UTAMA: 0,
      JUMLAH_KUNJUNGAN_RAWAT_INAP_PEREMPUAN_FASILITAS_PELAYANAN_KESEHATAN_TINGKAT_LANJUT_RS_UMUM: 0,
      JUMLAH_KUNJUNGAN_RAWAT_INAP_PEREMPUAN_FASILITAS_PELAYANAN_KESEHATAN_TINGKAT_LANJUT_RS_KHUSUS: 0,
      JUMLAH_KUNJUNGAN_RAWAT_INAP_PEREMPUAN_FASILITAS_PELAYANAN_KESEHATAN_TINGKAT_LANJUT_PRAKTIK_MANDIRI_DOKTER_SPESIALIS: 0,
      JUMLAH_KUNJUNGAN_RAWAT_INAP_LAKI_PEREMPUAN_FASILITAS_PELAYANAN_KESEHATAN_TINGKAT_PERTAMA_PUSKESMAS: 0,
      JUMLAH_KUNJUNGAN_RAWAT_INAP_LAKI_PEREMPUAN_FASILITAS_PELAYANAN_KESEHATAN_TINGKAT_PERTAMA_KLINIK_PRATAMA: 0,
      JUMLAH_KUNJUNGAN_RAWAT_INAP_LAKI_PEREMPUAN_FASILITAS_PELAYANAN_KESEHATAN_TINGKAT_PERTAMA_PRAKTIK_MANDIRI_DOKTER: 0,
      JUMLAH_KUNJUNGAN_RAWAT_INAP_LAKI_PEREMPUAN_FASILITAS_PELAYANAN_KESEHATAN_TINGKAT_PERTAMA_PRAKTIK_MANDIRI_DOKTER_GIGI: 0,
      JUMLAH_KUNJUNGAN_RAWAT_INAP_LAKI_PEREMPUAN_FASILITAS_PELAYANAN_KESEHATAN_TINGKAT_PERTAMA_PRAKTIK_MANDIRI_BIDAN: 0,
      JUMLAH_KUNJUNGAN_RAWAT_INAP_LAKI_PEREMPUAN_FASILITAS_PELAYANAN_KESEHATAN_TINGKAT_LANJUT_KLINIK_UTAMA: 0,
      JUMLAH_KUNJUNGAN_RAWAT_INAP_LAKI_PEREMPUAN_FASILITAS_PELAYANAN_KESEHATAN_TINGKAT_LANJUT_RS_UMUM: 0,
      JUMLAH_KUNJUNGAN_RAWAT_INAP_LAKI_PEREMPUAN_FASILITAS_PELAYANAN_KESEHATAN_TINGKAT_LANJUT_RS_KHUSUS: 0,
      JUMLAH_KUNJUNGAN_RAWAT_INAP_LAKI_PEREMPUAN_FASILITAS_PELAYANAN_KESEHATAN_TINGKAT_LANJUT_PRAKTIK_MANDIRI_DOKTER_SPESIALIS: 0,
      KUNJUNGAN_GANGGUAN_JIWA_JUMLAH_LAKI_FASILITAS_PELAYANAN_KESEHATAN_TINGKAT_PERTAMA_PUSKESMAS: 0,
      KUNJUNGAN_GANGGUAN_JIWA_JUMLAH_LAKI_FASILITAS_PELAYANAN_KESEHATAN_TINGKAT_PERTAMA_KLINIK_PRATAMA: 0,
      KUNJUNGAN_GANGGUAN_JIWA_JUMLAH_LAKI_FASILITAS_PELAYANAN_KESEHATAN_TINGKAT_PERTAMA_PRAKTIK_MANDIRI_DOKTER: 0,
      KUNJUNGAN_GANGGUAN_JIWA_JUMLAH_LAKI_FASILITAS_PELAYANAN_KESEHATAN_TINGKAT_PERTAMA_PRAKTIK_MANDIRI_DOKTER_GIGI: 0,
      KUNJUNGAN_GANGGUAN_JIWA_JUMLAH_LAKI_FASILITAS_PELAYANAN_KESEHATAN_TINGKAT_PERTAMA_PRAKTIK_MANDIRI_BIDAN: 0,
      KUNJUNGAN_GANGGUAN_JIWA_JUMLAH_LAKI_FASILITAS_PELAYANAN_KESEHATAN_TINGKAT_LANJUT_KLINIK_UTAMA: 0,
      KUNJUNGAN_GANGGUAN_JIWA_JUMLAH_LAKI_FASILITAS_PELAYANAN_KESEHATAN_TINGKAT_LANJUT_RS_UMUM: 0,
      KUNJUNGAN_GANGGUAN_JIWA_JUMLAH_LAKI_FASILITAS_PELAYANAN_KESEHATAN_TINGKAT_LANJUT_RS_KHUSUS: 0,
      KUNJUNGAN_GANGGUAN_JIWA_JUMLAH_LAKI_FASILITAS_PELAYANAN_KESEHATAN_TINGKAT_LANJUT_PRAKTIK_MANDIRI_DOKTER_SPESIALIS: 0,
      KUNJUNGAN_GANGGUAN_JIWA_JUMLAH_PEREMPUAN_FASILITAS_PELAYANAN_KESEHATAN_TINGKAT_PERTAMA_PUSKESMAS: 0,
      KUNJUNGAN_GANGGUAN_JIWA_JUMLAH_PEREMPUAN_FASILITAS_PELAYANAN_KESEHATAN_TINGKAT_PERTAMA_KLINIK_PRATAMA: 0,
      KUNJUNGAN_GANGGUAN_JIWA_JUMLAH_PEREMPUAN_FASILITAS_PELAYANAN_KESEHATAN_TINGKAT_PERTAMA_PRAKTIK_MANDIRI_DOKTER: 0,
      KUNJUNGAN_GANGGUAN_JIWA_JUMLAH_PEREMPUAN_FASILITAS_PELAYANAN_KESEHATAN_TINGKAT_PERTAMA_PRAKTIK_MANDIRI_DOKTER_GIGI: 0,
      KUNJUNGAN_GANGGUAN_JIWA_JUMLAH_PEREMPUAN_FASILITAS_PELAYANAN_KESEHATAN_TINGKAT_PERTAMA_PRAKTIK_MANDIRI_BIDAN: 0,
      KUNJUNGAN_GANGGUAN_JIWA_JUMLAH_PEREMPUAN_FASILITAS_PELAYANAN_KESEHATAN_TINGKAT_LANJUT_KLINIK_UTAMA: 0,
      KUNJUNGAN_GANGGUAN_JIWA_JUMLAH_PEREMPUAN_FASILITAS_PELAYANAN_KESEHATAN_TINGKAT_LANJUT_RS_UMUM: 0,
      KUNJUNGAN_GANGGUAN_JIWA_JUMLAH_PEREMPUAN_FASILITAS_PELAYANAN_KESEHATAN_TINGKAT_LANJUT_RS_KHUSUS: 0,
      KUNJUNGAN_GANGGUAN_JIWA_JUMLAH_PEREMPUAN_FASILITAS_PELAYANAN_KESEHATAN_TINGKAT_LANJUT_PRAKTIK_MANDIRI_DOKTER_SPESIALIS: 0,
      KUNJUNGAN_GANGGUAN_JIWA_JUMLAH_LAKI_PEREMPUAN_FASILITAS_PELAYANAN_KESEHATAN_TINGKAT_PERTAMA_PUSKESMAS: 0,
      KUNJUNGAN_GANGGUAN_JIWA_JUMLAH_LAKI_PEREMPUAN_FASILITAS_PELAYANAN_KESEHATAN_TINGKAT_PERTAMA_KLINIK_PRATAMA: 0,
      KUNJUNGAN_GANGGUAN_JIWA_JUMLAH_LAKI_PEREMPUAN_FASILITAS_PELAYANAN_KESEHATAN_TINGKAT_PERTAMA_PRAKTIK_MANDIRI_DOKTER: 0,
      KUNJUNGAN_GANGGUAN_JIWA_JUMLAH_LAKI_PEREMPUAN_FASILITAS_PELAYANAN_KESEHATAN_TINGKAT_PERTAMA_PRAKTIK_MANDIRI_DOKTER_GIGI: 0,
      KUNJUNGAN_GANGGUAN_JIWA_JUMLAH_LAKI_PEREMPUAN_FASILITAS_PELAYANAN_KESEHATAN_TINGKAT_PERTAMA_PRAKTIK_MANDIRI_BIDAN: 0,
      KUNJUNGAN_GANGGUAN_JIWA_JUMLAH_LAKI_PEREMPUAN_FASILITAS_PELAYANAN_KESEHATAN_TINGKAT_LANJUT_KLINIK_UTAMA: 0,
      KUNJUNGAN_GANGGUAN_JIWA_JUMLAH_LAKI_PEREMPUAN_FASILITAS_PELAYANAN_KESEHATAN_TINGKAT_LANJUT_RS_UMUM: 0,
      KUNJUNGAN_GANGGUAN_JIWA_JUMLAH_LAKI_PEREMPUAN_FASILITAS_PELAYANAN_KESEHATAN_TINGKAT_LANJUT_RS_KHUSUS: 0,
      KUNJUNGAN_GANGGUAN_JIWA_JUMLAH_LAKI_PEREMPUAN_FASILITAS_PELAYANAN_KESEHATAN_TINGKAT_LANJUT_PRAKTIK_MANDIRI_DOKTER_SPESIALIS: 0,     
      isUpdate: false  
    }    
  },
  methods: {
    initialData: function() {
      return {
        KUNJUNGAN_GANGGUAN_JIWA_JUMLAH_LP_FASILITAS_PELAYANAN_KESEHATAN_TINGKAT_LANJUT_RS_UMUM: 0,
        JUMLAH_KUNJUNGAN_RAWAT_JALAN_LAKI_FASILITAS_PELAYANAN_KESEHATAN_TINGKAT_PERTAMA_PUSKESMAS: 0,
        JUMLAH_KUNJUNGAN_RAWAT_JALAN_LAKI_FASILITAS_PELAYANAN_KESEHATAN_TINGKAT_PERTAMA_KLINIK_PRATAMA: 0,
        JUMLAH_KUNJUNGAN_RAWAT_JALAN_LAKI_FASILITAS_PELAYANAN_KESEHATAN_TINGKAT_PERTAMA_PRAKTIK_MANDIRI_DOKTER: 0,
        JUMLAH_KUNJUNGAN_RAWAT_JALAN_LAKI_FASILITAS_PELAYANAN_KESEHATAN_TINGKAT_PERTAMA_PRAKTIK_MANDIRI_DOKTER_GIGI: 0,
        JUMLAH_KUNJUNGAN_RAWAT_JALAN_LAKI_FASILITAS_PELAYANAN_KESEHATAN_TINGKAT_PERTAMA_PRAKTIK_MANDIRI_BIDAN: 0,
        JUMLAH_KUNJUNGAN_RAWAT_JALAN_LAKI_FASILITAS_PELAYANAN_KESEHATAN_TINGKAT_LANJUT_KLINIK_UTAMA: 0,
        JUMLAH_KUNJUNGAN_RAWAT_JALAN_LAKI_FASILITAS_PELAYANAN_KESEHATAN_TINGKAT_LANJUT_RS_UMUM: 0,
        JUMLAH_KUNJUNGAN_RAWAT_JALAN_LP_FASILITAS_PELAYANAN_KESEHATAN_TINGKAT_LANJUT_RS_UMUM: 0,
        JUMLAH_KUNJUNGAN_RAWAT_JALAN_LAKI_FASILITAS_PELAYANAN_KESEHATAN_TINGKAT_LANJUT_RS_KHUSUS: 0,
        JUMLAH_KUNJUNGAN_RAWAT_JALAN_LAKI_FASILITAS_PELAYANAN_KESEHATAN_TINGKAT_LANJUT_PRAKTIK_MANDIRI_DOKTER_SPESIALIS: 0,
        JUMLAH_KUNJUNGAN_RAWAT_JALAN_PEREMPUAN_FASILITAS_PELAYANAN_KESEHATAN_TINGKAT_PERTAMA_PUSKESMAS: 0,
        JUMLAH_KUNJUNGAN_RAWAT_JALAN_PEREMPUAN_FASILITAS_PELAYANAN_KESEHATAN_TINGKAT_PERTAMA_KLINIK_PRATAMA: 0,
        JUMLAH_KUNJUNGAN_RAWAT_JALAN_PEREMPUAN_FASILITAS_PELAYANAN_KESEHATAN_TINGKAT_PERTAMA_PRAKTIK_MANDIRI_DOKTER: 0,
        JUMLAH_KUNJUNGAN_RAWAT_JALAN_PEREMPUAN_FASILITAS_PELAYANAN_KESEHATAN_TINGKAT_PERTAMA_PRAKTIK_MANDIRI_DOKTER_GIGI: 0,
        JUMLAH_KUNJUNGAN_RAWAT_JALAN_PEREMPUAN_FASILITAS_PELAYANAN_KESEHATAN_TINGKAT_PERTAMA_PRAKTIK_MANDIRI_BIDAN: 0,
        JUMLAH_KUNJUNGAN_RAWAT_JALAN_PEREMPUAN_FASILITAS_PELAYANAN_KESEHATAN_TINGKAT_LANJUT_KLINIK_UTAMA: 0,
        JUMLAH_KUNJUNGAN_RAWAT_JALAN_PEREMPUAN_FASILITAS_PELAYANAN_KESEHATAN_TINGKAT_LANJUT_RS_UMUM: 0,
        JUMLAH_KUNJUNGAN_RAWAT_JALAN_PEREMPUAN_FASILITAS_PELAYANAN_KESEHATAN_TINGKAT_LANJUT_RS_KHUSUS: 0,
        JUMLAH_KUNJUNGAN_RAWAT_JALAN_PEREMPUAN_FASILITAS_PELAYANAN_KESEHATAN_TINGKAT_LANJUT_PRAKTIK_MANDIRI_DOKTER_SPESIALIS: 0,
        JUMLAH_KUNJUNGAN_RAWAT_JALAN_LAKI_PEREMPUAN_FASILITAS_PELAYANAN_KESEHATAN_TINGKAT_PERTAMA_PUSKESMAS: 0,
        JUMLAH_KUNJUNGAN_RAWAT_JALAN_LAKI_PEREMPUAN_FASILITAS_PELAYANAN_KESEHATAN_TINGKAT_PERTAMA_KLINIK_PRATAMA: 0,
        JUMLAH_KUNJUNGAN_RAWAT_JALAN_LAKI_PEREMPUAN_FASILITAS_PELAYANAN_KESEHATAN_TINGKAT_PERTAMA_PRAKTIK_MANDIRI_DOKTER: 0,
        JUMLAH_KUNJUNGAN_RAWAT_JALAN_LAKI_PEREMPUAN_FASILITAS_PELAYANAN_KESEHATAN_TINGKAT_PERTAMA_PRAKTIK_MANDIRI_DOKTER_GIGI: 0,
        JUMLAH_KUNJUNGAN_RAWAT_JALAN_LAKI_PEREMPUAN_FASILITAS_PELAYANAN_KESEHATAN_TINGKAT_PERTAMA_PRAKTIK_MANDIRI_BIDAN: 0,
        JUMLAH_KUNJUNGAN_RAWAT_JALAN_LAKI_PEREMPUAN_FASILITAS_PELAYANAN_KESEHATAN_TINGKAT_LANJUT_KLINIK_UTAMA: 0,
        JUMLAH_KUNJUNGAN_RAWAT_JALAN_LAKI_PEREMPUAN_FASILITAS_PELAYANAN_KESEHATAN_TINGKAT_LANJUT_RS_UMUM: 0,
        JUMLAH_KUNJUNGAN_RAWAT_JALAN_LAKI_PEREMPUAN_FASILITAS_PELAYANAN_KESEHATAN_TINGKAT_LANJUT_RS_KHUSUS: 0,
        JUMLAH_KUNJUNGAN_RAWAT_JALAN_LAKI_PEREMPUAN_FASILITAS_PELAYANAN_KESEHATAN_TINGKAT_LANJUT_PRAKTIK_MANDIRI_DOKTER_SPESIALIS: 0,
        JUMLAH_KUNJUNGAN_RAWAT_INAP_LAKI_FASILITAS_PELAYANAN_KESEHATAN_TINGKAT_PERTAMA_PUSKESMAS: 0,
        JUMLAH_KUNJUNGAN_RAWAT_INAP_LAKI_FASILITAS_PELAYANAN_KESEHATAN_TINGKAT_PERTAMA_KLINIK_PRATAMA: 0,
        JUMLAH_KUNJUNGAN_RAWAT_INAP_LAKI_FASILITAS_PELAYANAN_KESEHATAN_TINGKAT_PERTAMA_PRAKTIK_MANDIRI_DOKTER: 0,
        JUMLAH_KUNJUNGAN_RAWAT_INAP_LAKI_FASILITAS_PELAYANAN_KESEHATAN_TINGKAT_PERTAMA_PRAKTIK_MANDIRI_DOKTER_GIGI: 0,
        JUMLAH_KUNJUNGAN_RAWAT_INAP_LAKI_FASILITAS_PELAYANAN_KESEHATAN_TINGKAT_PERTAMA_PRAKTIK_MANDIRI_BIDAN: 0,
        JUMLAH_KUNJUNGAN_RAWAT_INAP_LAKI_FASILITAS_PELAYANAN_KESEHATAN_TINGKAT_LANJUT_KLINIK_UTAMA: 0,
        JUMLAH_KUNJUNGAN_RAWAT_INAP_LAKI_FASILITAS_PELAYANAN_KESEHATAN_TINGKAT_LANJUT_RS_UMUM: 0,
        JUMLAH_KUNJUNGAN_RAWAT_INAP_LAKI_FASILITAS_PELAYANAN_KESEHATAN_TINGKAT_LANJUT_RS_KHUSUS: 0,
        JUMLAH_KUNJUNGAN_RAWAT_INAP_LAKI_FASILITAS_PELAYANAN_KESEHATAN_TINGKAT_LANJUT_PRAKTIK_MANDIRI_DOKTER_SPESIALIS: 0,
        JUMLAH_KUNJUNGAN_RAWAT_INAP_PEREMPUAN_FASILITAS_PELAYANAN_KESEHATAN_TINGKAT_PERTAMA_PUSKESMAS: 0,
        JUMLAH_KUNJUNGAN_RAWAT_INAP_PEREMPUAN_FASILITAS_PELAYANAN_KESEHATAN_TINGKAT_PERTAMA_KLINIK_PRATAMA: 0,
        JUMLAH_KUNJUNGAN_RAWAT_INAP_PEREMPUAN_FASILITAS_PELAYANAN_KESEHATAN_TINGKAT_PERTAMA_PRAKTIK_MANDIRI_DOKTER: 0,
        JUMLAH_KUNJUNGAN_RAWAT_INAP_PEREMPUAN_FASILITAS_PELAYANAN_KESEHATAN_TINGKAT_PERTAMA_PRAKTIK_MANDIRI_DOKTER_GIGI: 0,
        JUMLAH_KUNJUNGAN_RAWAT_INAP_PEREMPUAN_FASILITAS_PELAYANAN_KESEHATAN_TINGKAT_PERTAMA_PRAKTIK_MANDIRI_BIDAN: 0,
        JUMLAH_KUNJUNGAN_RAWAT_INAP_PEREMPUAN_FASILITAS_PELAYANAN_KESEHATAN_TINGKAT_LANJUT_KLINIK_UTAMA: 0,
        JUMLAH_KUNJUNGAN_RAWAT_INAP_PEREMPUAN_FASILITAS_PELAYANAN_KESEHATAN_TINGKAT_LANJUT_RS_UMUM: 0,
        JUMLAH_KUNJUNGAN_RAWAT_INAP_PEREMPUAN_FASILITAS_PELAYANAN_KESEHATAN_TINGKAT_LANJUT_RS_KHUSUS: 0,
        JUMLAH_KUNJUNGAN_RAWAT_INAP_PEREMPUAN_FASILITAS_PELAYANAN_KESEHATAN_TINGKAT_LANJUT_PRAKTIK_MANDIRI_DOKTER_SPESIALIS: 0,
        JUMLAH_KUNJUNGAN_RAWAT_INAP_LAKI_PEREMPUAN_FASILITAS_PELAYANAN_KESEHATAN_TINGKAT_PERTAMA_PUSKESMAS: 0,
        JUMLAH_KUNJUNGAN_RAWAT_INAP_LAKI_PEREMPUAN_FASILITAS_PELAYANAN_KESEHATAN_TINGKAT_PERTAMA_KLINIK_PRATAMA: 0,
        JUMLAH_KUNJUNGAN_RAWAT_INAP_LAKI_PEREMPUAN_FASILITAS_PELAYANAN_KESEHATAN_TINGKAT_PERTAMA_PRAKTIK_MANDIRI_DOKTER: 0,
        JUMLAH_KUNJUNGAN_RAWAT_INAP_LAKI_PEREMPUAN_FASILITAS_PELAYANAN_KESEHATAN_TINGKAT_PERTAMA_PRAKTIK_MANDIRI_DOKTER_GIGI: 0,
        JUMLAH_KUNJUNGAN_RAWAT_INAP_LAKI_PEREMPUAN_FASILITAS_PELAYANAN_KESEHATAN_TINGKAT_PERTAMA_PRAKTIK_MANDIRI_BIDAN: 0,
        JUMLAH_KUNJUNGAN_RAWAT_INAP_LAKI_PEREMPUAN_FASILITAS_PELAYANAN_KESEHATAN_TINGKAT_LANJUT_KLINIK_UTAMA: 0,
        JUMLAH_KUNJUNGAN_RAWAT_INAP_LAKI_PEREMPUAN_FASILITAS_PELAYANAN_KESEHATAN_TINGKAT_LANJUT_RS_UMUM: 0,
        JUMLAH_KUNJUNGAN_RAWAT_INAP_LAKI_PEREMPUAN_FASILITAS_PELAYANAN_KESEHATAN_TINGKAT_LANJUT_RS_KHUSUS: 0,
        JUMLAH_KUNJUNGAN_RAWAT_INAP_LAKI_PEREMPUAN_FASILITAS_PELAYANAN_KESEHATAN_TINGKAT_LANJUT_PRAKTIK_MANDIRI_DOKTER_SPESIALIS: 0,
        KUNJUNGAN_GANGGUAN_JIWA_JUMLAH_LAKI_FASILITAS_PELAYANAN_KESEHATAN_TINGKAT_PERTAMA_PUSKESMAS: 0,
        KUNJUNGAN_GANGGUAN_JIWA_JUMLAH_LAKI_FASILITAS_PELAYANAN_KESEHATAN_TINGKAT_PERTAMA_KLINIK_PRATAMA: 0,
        KUNJUNGAN_GANGGUAN_JIWA_JUMLAH_LAKI_FASILITAS_PELAYANAN_KESEHATAN_TINGKAT_PERTAMA_PRAKTIK_MANDIRI_DOKTER: 0,
        KUNJUNGAN_GANGGUAN_JIWA_JUMLAH_LAKI_FASILITAS_PELAYANAN_KESEHATAN_TINGKAT_PERTAMA_PRAKTIK_MANDIRI_DOKTER_GIGI: 0,
        KUNJUNGAN_GANGGUAN_JIWA_JUMLAH_LAKI_FASILITAS_PELAYANAN_KESEHATAN_TINGKAT_PERTAMA_PRAKTIK_MANDIRI_BIDAN: 0,
        KUNJUNGAN_GANGGUAN_JIWA_JUMLAH_LAKI_FASILITAS_PELAYANAN_KESEHATAN_TINGKAT_LANJUT_KLINIK_UTAMA: 0,
        KUNJUNGAN_GANGGUAN_JIWA_JUMLAH_LAKI_FASILITAS_PELAYANAN_KESEHATAN_TINGKAT_LANJUT_RS_UMUM: 0,
        KUNJUNGAN_GANGGUAN_JIWA_JUMLAH_LAKI_FASILITAS_PELAYANAN_KESEHATAN_TINGKAT_LANJUT_RS_KHUSUS: 0,
        KUNJUNGAN_GANGGUAN_JIWA_JUMLAH_LAKI_FASILITAS_PELAYANAN_KESEHATAN_TINGKAT_LANJUT_PRAKTIK_MANDIRI_DOKTER_SPESIALIS: 0,
        KUNJUNGAN_GANGGUAN_JIWA_JUMLAH_PEREMPUAN_FASILITAS_PELAYANAN_KESEHATAN_TINGKAT_PERTAMA_PUSKESMAS: 0,
        KUNJUNGAN_GANGGUAN_JIWA_JUMLAH_PEREMPUAN_FASILITAS_PELAYANAN_KESEHATAN_TINGKAT_PERTAMA_KLINIK_PRATAMA: 0,
        KUNJUNGAN_GANGGUAN_JIWA_JUMLAH_PEREMPUAN_FASILITAS_PELAYANAN_KESEHATAN_TINGKAT_PERTAMA_PRAKTIK_MANDIRI_DOKTER: 0,
        KUNJUNGAN_GANGGUAN_JIWA_JUMLAH_PEREMPUAN_FASILITAS_PELAYANAN_KESEHATAN_TINGKAT_PERTAMA_PRAKTIK_MANDIRI_DOKTER_GIGI: 0,
        KUNJUNGAN_GANGGUAN_JIWA_JUMLAH_PEREMPUAN_FASILITAS_PELAYANAN_KESEHATAN_TINGKAT_PERTAMA_PRAKTIK_MANDIRI_BIDAN: 0,
        KUNJUNGAN_GANGGUAN_JIWA_JUMLAH_PEREMPUAN_FASILITAS_PELAYANAN_KESEHATAN_TINGKAT_LANJUT_KLINIK_UTAMA: 0,
        KUNJUNGAN_GANGGUAN_JIWA_JUMLAH_PEREMPUAN_FASILITAS_PELAYANAN_KESEHATAN_TINGKAT_LANJUT_RS_UMUM: 0,
        KUNJUNGAN_GANGGUAN_JIWA_JUMLAH_PEREMPUAN_FASILITAS_PELAYANAN_KESEHATAN_TINGKAT_LANJUT_RS_KHUSUS: 0,
        KUNJUNGAN_GANGGUAN_JIWA_JUMLAH_PEREMPUAN_FASILITAS_PELAYANAN_KESEHATAN_TINGKAT_LANJUT_PRAKTIK_MANDIRI_DOKTER_SPESIALIS: 0,
        KUNJUNGAN_GANGGUAN_JIWA_JUMLAH_LAKI_PEREMPUAN_FASILITAS_PELAYANAN_KESEHATAN_TINGKAT_PERTAMA_PUSKESMAS: 0,
        KUNJUNGAN_GANGGUAN_JIWA_JUMLAH_LAKI_PEREMPUAN_FASILITAS_PELAYANAN_KESEHATAN_TINGKAT_PERTAMA_KLINIK_PRATAMA: 0,
        KUNJUNGAN_GANGGUAN_JIWA_JUMLAH_LAKI_PEREMPUAN_FASILITAS_PELAYANAN_KESEHATAN_TINGKAT_PERTAMA_PRAKTIK_MANDIRI_DOKTER: 0,
        KUNJUNGAN_GANGGUAN_JIWA_JUMLAH_LAKI_PEREMPUAN_FASILITAS_PELAYANAN_KESEHATAN_TINGKAT_PERTAMA_PRAKTIK_MANDIRI_DOKTER_GIGI: 0,
        KUNJUNGAN_GANGGUAN_JIWA_JUMLAH_LAKI_PEREMPUAN_FASILITAS_PELAYANAN_KESEHATAN_TINGKAT_PERTAMA_PRAKTIK_MANDIRI_BIDAN: 0,
        KUNJUNGAN_GANGGUAN_JIWA_JUMLAH_LAKI_PEREMPUAN_FASILITAS_PELAYANAN_KESEHATAN_TINGKAT_LANJUT_KLINIK_UTAMA: 0,
        KUNJUNGAN_GANGGUAN_JIWA_JUMLAH_LAKI_PEREMPUAN_FASILITAS_PELAYANAN_KESEHATAN_TINGKAT_LANJUT_RS_UMUM: 0,
        KUNJUNGAN_GANGGUAN_JIWA_JUMLAH_LAKI_PEREMPUAN_FASILITAS_PELAYANAN_KESEHATAN_TINGKAT_LANJUT_RS_KHUSUS: 0,
        KUNJUNGAN_GANGGUAN_JIWA_JUMLAH_LAKI_PEREMPUAN_FASILITAS_PELAYANAN_KESEHATAN_TINGKAT_LANJUT_PRAKTIK_MANDIRI_DOKTER_SPESIALIS: 0          
      }
    },
    cariTanggal: function() {
      this.checkData(this.$data);
    },
    reset: function() {
      this.$dialogs.confirm('Apakah anda yakin ingin menghapus data?', 
      {title: 'Info', size: 'sm'})
      .then(res => {
        console.log(res) // {ok: true|false|undefined}
        if(res.ok == true) {
          for (var key in this.$data) {
            this.$http.get(this.$urlNode + '/table/delete?var='+key+'&thn='+this.PILIH_TAHUN+'&bln=' + this.PILIH_BULAN + '&username=' + this.USERNAME)
              .then(function (response) {
                // console.log(response);
              })
              .catch(function (error) {
                // console.log(error);
                return false;
              });
          }          
        }
      })      
    },
  
    checkData: function(data) {
      for (var key in data) {
        this.$http.get(this.$urlNode + '/table/getField?var=' + key + '&thn='+this.PILIH_TAHUN+'&bln=' + this.PILIH_BULAN + '&username=' + this.USERNAME)
          .then((response) => {
            console.log(response)
            if(response.data.length > 0) {
              // Read All Data
              this[response.data[0].NAMA_FIELD] = response.data[0].VALUE;
            } else {
              // Reset All Data
              Object.assign(this.$data, this.initialData());
            }
          })
          .catch(function (error) {
            console.log(error);
          });
      }
    }             
  },
  components: {},
  created() {
    var user = JSON.parse(this.$session.get('dataLogin'));
    this.NAMA_RUMAH_SAKIT = user.NAMA_RS;    
    this.USERNAME = user.username;    
  }
}
</script>